services:
  - type: web
    name: pornsearch-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NPM_VERSION
        value: 9.5.1
      - key: PORT
        value: 10000
      - key: CHROME_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
